#
# Copyright (c) 2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Aria2-Pro-Core
#

name: Aria2 Builder

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        PLATFORMS: [amd64, arm64, armhf, i386]
        include:
        - PLATFORMS: amd64
          BUILDER_IMAGE: debian:12
          BUILD_SCRIPT: aria2-gnu-linux-build-amd64.sh
        - PLATFORMS: arm64
          BUILDER_IMAGE: debian:12
          BUILD_SCRIPT: aria2-gnu-linux-cross-build-arm64.sh
        - PLATFORMS: armhf
          BUILDER_IMAGE: ubuntu:24.04
          BUILD_SCRIPT: aria2-gnu-linux-cross-build-armhf.sh
        - PLATFORMS: i386
          BUILDER_IMAGE: debian:10
          BUILD_SCRIPT: aria2-gnu-linux-cross-build-i386.sh

    steps:
    - name: set variables
      run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      shell: bash

    - name: Install QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      env:
        DOCKER_BUILDKIT: 1
        BUILDER_IMAGE: ${{ matrix.BUILDER_IMAGE }}
        BUILD_SCRIPT: ${{ matrix.BUILD_SCRIPT }}
      run: |
        docker build \
          --build-arg BUILDER_IMAGE \
          --build-arg BUILD_SCRIPT \
          --platform=local \
          -o ./ . \
          2>&1 | tee build.log

    - name: Output Error Log
      if: (!cancelled())
      run: grep -iE 'fatal|error|critical|failure|warning' build.log

    - name: Check Version
      run: |
        tar xzvf ./aria2*.tar.gz
        file aria2c 2>&1 | tee ./file-type-${{ matrix.PLATFORMS }}.txt
        ./aria2c -v 2>&1 | tee ./version-${{ matrix.PLATFORMS }}.txt
   
    - name: Git push assets to "release" branch
      run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add ./*.tar.gz
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

    - name: Release and upload assets
      run: |
          gh release create ${{ env.TAG_NAME }} --generate-notes --latest --title ${{ env.RELEASE_NAME }} ./*.tar.gz
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Functional Testing
      run: |
        ./aria2c https://raw.githubusercontent.com/P3TERX/aria2.conf/master/dht.dat
        ./aria2c https://raw.githubusercontent.com/P3TERX/aria2.conf/master/dht6.dat
